import type { ProjectType } from './types'

const t = (ar: string, en: string) => ({ ar, en })

export const PROJECT_TYPES: ProjectType[] = [
  {
    id: 'design',
    icon: 'Palette',
    label: t('تصميم', 'Design'),
    description: t('شعارات، هوية بصرية، بوسترات، واجهات', 'Logos, branding, posters, UI'),
    isVisual: true,
    personaRole: t('مصمم جرافيك محترف بخبرة عشر سنوات', 'a professional graphic designer with 10 years of experience'),
    questions: [
      {
        id: 'designKind',
        label: t('ما نوع التصميم المطلوب؟', 'What kind of design do you need?'),
        type: 'select',
        required: true,
        options: [
          { value: 'logo', label: t('شعار', 'Logo') },
          { value: 'branding', label: t('هوية بصرية كاملة', 'Full branding / identity') },
          { value: 'poster', label: t('بوستر / فلاير', 'Poster / flyer') },
          { value: 'ui', label: t('واجهة تطبيق أو موقع', 'App / web UI screen') },
          { value: 'packaging', label: t('تغليف منتج', 'Packaging') },
          { value: 'social', label: t('منشور سوشيال ميديا', 'Social media post') },
          { value: 'illustration', label: t('رسمة / إيلستريشن', 'Illustration') },
          { value: 'other', label: t('أخرى', 'Other') },
        ],
      },
      {
        id: 'brandInfo',
        label: t('حدّثني عن المشروع أو العلامة التجارية', 'Tell me about the project or brand'),
        placeholder: t('الاسم، المجال، الجمهور، الشخصية المطلوبة...', 'Name, industry, audience, desired personality...'),
        type: 'textarea',
        required: true,
      },
      {
        id: 'style',
        label: t('ما الأسلوب البصري المفضل؟', 'What visual style do you prefer?'),
        type: 'select',
        required: true,
        options: [
          { value: 'minimal', label: t('بسيط / مينيمال', 'Minimal') },
          { value: 'modern', label: t('عصري', 'Modern') },
          { value: 'luxury', label: t('فاخر', 'Luxury') },
          { value: 'playful', label: t('مرح', 'Playful') },
          { value: 'vintage', label: t('كلاسيكي / ريترو', 'Vintage / retro') },
          { value: 'corporate', label: t('رسمي / مؤسسي', 'Corporate') },
          { value: 'organic', label: t('طبيعي / يدوي', 'Organic / handmade') },
          { value: 'futuristic', label: t('مستقبلي', 'Futuristic') },
        ],
      },
      {
        id: 'colors',
        label: t('ألوان العلامة أو التفضيلات اللونية', 'Brand colors or color preferences'),
        placeholder: t('مثال: أزرق داكن وذهبي', 'e.g. navy blue and gold'),
        type: 'text',
        required: false,
      },
      {
        id: 'deliverable',
        label: t('المخرجات المطلوبة والمقاسات', 'Deliverable format and sizes'),
        placeholder: t('PNG شفاف 1080×1080، ملف قابل للطباعة...', 'Transparent PNG 1080x1080, print-ready file...'),
        type: 'text',
        required: false,
      },
    ],
  },
  {
    id: 'game',
    icon: 'Gamepad2',
    label: t('لعبة', 'Game'),
    description: t('تصميم ألعاب، ميكانيكا، فن اللعبة', 'Game design, mechanics, art'),
    isVisual: true,
    personaRole: t('مصمم ألعاب ومطور خبير', 'an expert game designer and developer'),
    questions: [
      {
        id: 'gameGenre',
        label: t('ما نوع اللعبة؟', 'What genre is the game?'),
        type: 'select',
        required: true,
        options: [
          { value: 'platformer', label: t('منصات', 'Platformer') },
          { value: 'rpg', label: t('آر بي جي', 'RPG') },
          { value: 'puzzle', label: t('ألغاز', 'Puzzle') },
          { value: 'shooter', label: t('إطلاق نار', 'Shooter') },
          { value: 'strategy', label: t('استراتيجية', 'Strategy') },
          { value: 'racing', label: t('سباقات', 'Racing') },
          { value: 'simulation', label: t('محاكاة', 'Simulation') },
          { value: 'horror', label: t('رعب', 'Horror') },
          { value: 'other', label: t('أخرى', 'Other') },
        ],
      },
      {
        id: 'platform',
        label: t('منصة اللعبة', 'Target platform'),
        type: 'select',
        required: true,
        options: [
          { value: 'pc', label: t('كمبيوتر', 'PC') },
          { value: 'mobile', label: t('موبايل', 'Mobile') },
          { value: 'console', label: t('كونسول', 'Console') },
          { value: 'web', label: t('ويب', 'Web') },
          { value: 'vr', label: t('واقع افتراضي', 'VR') },
        ],
      },
      {
        id: 'artStyle',
        label: t('الأسلوب الفني للعبة', 'Art style'),
        type: 'select',
        required: true,
        options: [
          { value: 'pixel', label: t('بيكسل آرت', 'Pixel art') },
          { value: 'lowpoly', label: t('لو بولي', 'Low poly') },
          { value: 'realistic', label: t('واقعي', 'Realistic') },
          { value: 'cartoon', label: t('كرتوني', 'Cartoon') },
          { value: 'anime', label: t('أنمي', 'Anime') },
          { value: 'handdrawn', label: t('مرسوم يدويًا', 'Hand-drawn') },
        ],
      },
      {
        id: 'mechanics',
        label: t('صف فكرة اللعبة وأهم آليات اللعب', 'Describe the game idea and core mechanics'),
        placeholder: t('القصة، طريقة اللعب، الهدف من كل مرحلة...', 'Story, gameplay loop, level goals...'),
        type: 'textarea',
        required: true,
      },
      {
        id: 'targetAudience',
        label: t('الفئة المستهدفة', 'Target audience'),
        placeholder: t('أطفال، مراهقون، لاعبون محترفون...', 'Kids, teens, hardcore gamers...'),
        type: 'text',
        required: false,
      },
    ],
  },
  {
    id: 'video',
    icon: 'Clapperboard',
    label: t('فيديو', 'Video'),
    description: t('إعلانات، سيناريو، محتوى مرئي', 'Ads, scripts, video content'),
    isVisual: true,
    personaRole: t('مخرج ومنتج فيديو محترف', 'a professional video director and producer'),
    questions: [
      {
        id: 'videoType',
        label: t('ما نوع الفيديو؟', 'What type of video?'),
        type: 'select',
        required: true,
        options: [
          { value: 'ad', label: t('إعلان تجاري', 'Ad / commercial') },
          { value: 'explainer', label: t('فيديو توضيحي', 'Explainer') },
          { value: 'tutorial', label: t('تعليمي', 'Tutorial') },
          { value: 'short-film', label: t('فيلم قصير', 'Short film') },
          { value: 'social', label: t('ريلز / تيك توك', 'Social reel / TikTok') },
          { value: 'vlog', label: t('فلوق', 'Vlog') },
          { value: 'documentary', label: t('وثائقي', 'Documentary') },
          { value: 'product-demo', label: t('عرض منتج', 'Product demo') },
        ],
      },
      {
        id: 'concept',
        label: t('فكرة الفيديو والرسالة الأساسية', 'The video idea and core message'),
        type: 'textarea',
        required: true,
      },
      {
        id: 'platform',
        label: t('منصة النشر', 'Publishing platform'),
        type: 'select',
        required: false,
        options: [
          { value: 'youtube', label: t('يوتيوب', 'YouTube') },
          { value: 'tiktok', label: t('تيك توك / ريلز', 'TikTok / Reels') },
          { value: 'instagram', label: t('إنستغرام', 'Instagram') },
          { value: 'linkedin', label: t('لينكدإن', 'LinkedIn') },
          { value: 'tv', label: t('تلفزيون / سينما', 'TV / cinema') },
        ],
      },
      {
        id: 'duration',
        label: t('المدة التقريبية', 'Approximate duration'),
        placeholder: t('15 ثانية، دقيقتان...', '15 seconds, 2 minutes...'),
        type: 'text',
        required: false,
      },
      {
        id: 'toneStyle',
        label: t('نبرة الفيديو', 'Tone / style'),
        type: 'select',
        required: true,
        options: [
          { value: 'energetic', label: t('حماسي', 'Energetic') },
          { value: 'emotional', label: t('عاطفي', 'Emotional') },
          { value: 'professional', label: t('احترافي', 'Professional') },
          { value: 'funny', label: t('كوميدي', 'Funny') },
          { value: 'cinematic', label: t('سينمائي', 'Cinematic') },
          { value: 'minimal', label: t('بسيط وهادئ', 'Minimal / calm') },
        ],
      },
    ],
  },
  {
    id: 'programming',
    icon: 'Code2',
    label: t('برمجة', 'Programming'),
    description: t('مهام برمجية، أكواد، مراجعة', 'Coding tasks, code, reviews'),
    isVisual: false,
    personaRole: t('مهندس برمجيات خبير', 'a senior software engineer'),
    questions: [
      {
        id: 'taskType',
        label: t('ما نوع المهمة البرمجية؟', 'What kind of coding task is this?'),
        type: 'select',
        required: true,
        options: [
          { value: 'new-feature', label: t('بناء ميزة جديدة', 'Build a new feature') },
          { value: 'bug-fix', label: t('إصلاح خطأ (Bug)', 'Fix a bug') },
          { value: 'refactor', label: t('إعادة هيكلة الكود', 'Refactor code') },
          { value: 'tests', label: t('كتابة اختبارات', 'Write tests') },
          { value: 'review', label: t('مراجعة كود', 'Code review') },
          { value: 'architecture', label: t('تصميم معماري', 'Architecture / design') },
          { value: 'docs', label: t('كتابة توثيق', 'Write documentation') },
          { value: 'explain', label: t('شرح كود', 'Explain code') },
        ],
      },
      {
        id: 'stack',
        label: t('اللغة أو الإطار المستخدم', 'Language / framework / stack'),
        placeholder: t('TypeScript, React, Node.js...', 'TypeScript, React, Node.js...'),
        type: 'text',
        required: true,
      },
      {
        id: 'context',
        label: t('صف المهمة والسياق الحالي للكود', 'Describe the task and current code context'),
        type: 'textarea',
        required: true,
      },
      {
        id: 'acceptance',
        label: t('معايير القبول / السلوك المتوقع', 'Acceptance criteria / expected behavior'),
        type: 'textarea',
        required: false,
      },
      {
        id: 'constraints',
        label: t('قيود أو متطلبات إضافية', 'Constraints or extra requirements'),
        placeholder: t('الأداء، التوافق، عدم استخدام مكتبات خارجية...', 'Performance, compatibility, no external libraries...'),
        type: 'textarea',
        required: false,
      },
    ],
  },
  {
    id: 'marketing',
    icon: 'Megaphone',
    label: t('تسويق', 'Marketing'),
    description: t('حملات، إعلانات، محتوى تسويقي', 'Campaigns, ads, marketing copy'),
    isVisual: true,
    personaRole: t('خبير تسويق ومحتوى إعلاني', 'an expert marketing and copywriting strategist'),
    questions: [
      {
        id: 'campaignType',
        label: t('نوع المحتوى التسويقي', 'What kind of marketing content?'),
        type: 'select',
        required: true,
        options: [
          { value: 'social-post', label: t('منشور سوشيال ميديا', 'Social media post') },
          { value: 'ad-copy', label: t('نص إعلاني', 'Ad copy') },
          { value: 'email', label: t('حملة إيميل', 'Email campaign') },
          { value: 'landing', label: t('محتوى صفحة هبوط', 'Landing page copy') },
          { value: 'product-desc', label: t('وصف منتج', 'Product description') },
          { value: 'press-release', label: t('بيان صحفي', 'Press release') },
          { value: 'slogan', label: t('شعار / تاجلاين', 'Slogan / tagline') },
        ],
      },
      {
        id: 'product',
        label: t('المنتج أو الخدمة والعرض الأساسي', 'The product/service and key offer'),
        type: 'textarea',
        required: true,
      },
      {
        id: 'targetAudience',
        label: t('الجمهور المستهدف', 'Target audience'),
        type: 'textarea',
        required: true,
      },
      {
        id: 'platform',
        label: t('المنصة', 'Platform'),
        type: 'select',
        required: false,
        options: [
          { value: 'instagram', label: t('إنستغرام', 'Instagram') },
          { value: 'facebook', label: t('فيسبوك', 'Facebook') },
          { value: 'x', label: t('إكس / تويتر', 'X / Twitter') },
          { value: 'linkedin', label: t('لينكدإن', 'LinkedIn') },
          { value: 'tiktok', label: t('تيك توك', 'TikTok') },
          { value: 'email', label: t('إيميل', 'Email') },
          { value: 'google-ads', label: t('إعلانات جوجل', 'Google Ads') },
        ],
      },
      {
        id: 'cta',
        label: t('الدعوة لاتخاذ إجراء (CTA)', 'Call to action'),
        placeholder: t('اطلب الآن، سجّل مجانًا...', 'Order now, sign up free...'),
        type: 'text',
        required: false,
      },
      {
        id: 'tone',
        label: t('نبرة الرسالة', 'Tone of voice'),
        type: 'select',
        required: true,
        options: [
          { value: 'persuasive', label: t('مقنعة', 'Persuasive') },
          { value: 'friendly', label: t('ودّية', 'Friendly') },
          { value: 'luxury', label: t('فاخرة', 'Luxury') },
          { value: 'urgent', label: t('ملحّة', 'Urgent') },
          { value: 'playful', label: t('مرحة', 'Playful') },
          { value: 'authoritative', label: t('موثوقة وسلطوية', 'Authoritative') },
        ],
      },
    ],
  },
  {
    id: 'image',
    icon: 'Image',
    label: t('صورة', 'Image'),
    description: t('توليد صور بالذكاء الاصطناعي', 'AI image generation'),
    isVisual: true,
    personaRole: t('فنان ومخرج بصري متخصص في التوليد بالذكاء الاصطناعي', 'a visual artist and art director specialized in AI generation'),
    questions: [
      {
        id: 'subject',
        label: t('ما الموضوع الرئيسي للصورة؟', 'What is the main subject of the image?'),
        type: 'textarea',
        required: true,
      },
      {
        id: 'style',
        label: t('الأسلوب الفني', 'Art style'),
        type: 'select',
        required: true,
        options: [
          { value: 'photorealistic', label: t('واقعي فوتوغرافي', 'Photorealistic') },
          { value: 'digital-art', label: t('فن رقمي', 'Digital art') },
          { value: 'illustration', label: t('إيلستريشن', 'Illustration') },
          { value: '3d', label: t('رندر ثلاثي الأبعاد', '3D render') },
          { value: 'anime', label: t('أنمي', 'Anime') },
          { value: 'watercolor', label: t('ألوان مائية', 'Watercolor') },
          { value: 'oil-painting', label: t('لوحة زيتية', 'Oil painting') },
          { value: 'cyberpunk', label: t('سايبربانك', 'Cyberpunk') },
          { value: 'minimalist', label: t('مينيمال', 'Minimalist') },
        ],
      },
      {
        id: 'composition',
        label: t('زاوية التصوير والتكوين', 'Camera angle / composition'),
        placeholder: t('لقطة قريبة، من الأعلى، بورتريه...', 'Close-up, top-down, portrait shot...'),
        type: 'text',
        required: false,
      },
      {
        id: 'lighting',
        label: t('الإضاءة', 'Lighting'),
        type: 'select',
        required: false,
        options: [
          { value: 'natural', label: t('طبيعية', 'Natural') },
          { value: 'studio', label: t('استوديو', 'Studio') },
          { value: 'cinematic', label: t('سينمائية', 'Cinematic') },
          { value: 'golden-hour', label: t('الساعة الذهبية', 'Golden hour') },
          { value: 'neon', label: t('نيون', 'Neon') },
          { value: 'dramatic', label: t('درامية', 'Dramatic') },
          { value: 'soft', label: t('ناعمة', 'Soft') },
        ],
      },
      {
        id: 'colorPalette',
        label: t('لوحة الألوان', 'Color palette'),
        type: 'text',
        required: false,
      },
      {
        id: 'mood',
        label: t('المزاج العام للصورة', 'Overall mood'),
        placeholder: t('هادئ، غامض، مبهج، مخيف...', 'Calm, mysterious, joyful, eerie...'),
        type: 'text',
        required: false,
      },
      {
        id: 'aspectRatio',
        label: t('نسبة الأبعاد', 'Aspect ratio'),
        type: 'select',
        required: false,
        options: [
          { value: '1:1', label: t('مربع 1:1', 'Square 1:1') },
          { value: '4:5', label: t('عمودي 4:5', 'Portrait 4:5') },
          { value: '16:9', label: t('عريض 16:9', 'Widescreen 16:9') },
          { value: '9:16', label: t('طولي 9:16', 'Vertical 9:16') },
          { value: '21:9', label: t('سينمائي 21:9', 'Cinematic 21:9') },
        ],
      },
      {
        id: 'negativeElements',
        label: t('عناصر تريد استبعادها', 'Elements you want to avoid'),
        placeholder: t('نص، تشوهات، أيدٍ إضافية...', 'Text, blur, extra fingers...'),
        type: 'text',
        required: false,
      },
    ],
  },
  {
    id: 'website',
    icon: 'LayoutTemplate',
    label: t('موقع إلكتروني', 'Website'),
    description: t('صفحات هبوط، متاجر، تطبيقات ويب', 'Landing pages, stores, web apps'),
    isVisual: true,
    personaRole: t('مصمم ومطور واجهات ويب محترف', 'a professional web designer and front-end developer'),
    questions: [
      {
        id: 'siteType',
        label: t('نوع الموقع', 'Type of website'),
        type: 'select',
        required: true,
        options: [
          { value: 'landing', label: t('صفحة هبوط', 'Landing page') },
          { value: 'ecommerce', label: t('متجر إلكتروني', 'E-commerce') },
          { value: 'portfolio', label: t('معرض أعمال', 'Portfolio') },
          { value: 'blog', label: t('مدونة', 'Blog') },
          { value: 'saas', label: t('تطبيق ويب SaaS', 'SaaS web app') },
          { value: 'corporate', label: t('موقع شركة', 'Corporate site') },
          { value: 'booking', label: t('حجز / خدمات', 'Booking / services') },
        ],
      },
      {
        id: 'purpose',
        label: t('الغرض من الموقع والجمهور المستهدف', 'Purpose of the site and target audience'),
        type: 'textarea',
        required: true,
      },
      {
        id: 'pages',
        label: t('الصفحات أو الأقسام المطلوبة', 'Required pages / sections'),
        placeholder: t('الرئيسية، من نحن، الخدمات، تواصل...', 'Home, about, services, contact...'),
        type: 'textarea',
        required: false,
      },
      {
        id: 'styleVibe',
        label: t('الطابع البصري', 'Visual style'),
        type: 'select',
        required: true,
        options: [
          { value: 'minimal', label: t('مينيمال', 'Minimal') },
          { value: 'corporate', label: t('مؤسسي', 'Corporate') },
          { value: 'playful', label: t('مرح', 'Playful') },
          { value: 'luxury', label: t('فاخر', 'Luxury') },
          { value: 'tech', label: t('تقني مستقبلي', 'Tech / futuristic') },
          { value: 'warm', label: t('دافئ وعضوي', 'Warm / organic') },
        ],
      },
      {
        id: 'keyFeatures',
        label: t('ميزات أساسية مطلوبة', 'Key features needed'),
        placeholder: t('نظام دفع، تسجيل دخول، لوحة تحكم...', 'Payments, login, dashboard...'),
        type: 'textarea',
        required: false,
      },
      {
        id: 'techPreference',
        label: t('تقنيات مفضلة (اختياري)', 'Preferred tech stack (optional)'),
        type: 'text',
        required: false,
      },
    ],
  },
  {
    id: 'writing',
    icon: 'PenLine',
    label: t('كتابة ومحتوى', 'Writing'),
    description: t('مقالات، قصص، محتوى نصي', 'Articles, stories, written content'),
    isVisual: false,
    personaRole: t('كاتب محتوى محترف', 'a professional content writer'),
    questions: [
      {
        id: 'contentType',
        label: t('نوع المحتوى', 'Type of content'),
        type: 'select',
        required: true,
        options: [
          { value: 'blog', label: t('مقال مدونة', 'Blog post') },
          { value: 'article', label: t('مقالة', 'Article') },
          { value: 'story', label: t('قصة / رواية', 'Story / fiction') },
          { value: 'script', label: t('سيناريو', 'Script') },
          { value: 'product-copy', label: t('نص منتج', 'Product copy') },
          { value: 'caption', label: t('تعليق سوشيال ميديا', 'Social caption') },
          { value: 'email', label: t('إيميل', 'Email') },
          { value: 'speech', label: t('خطاب', 'Speech') },
          { value: 'academic', label: t('أكاديمي', 'Academic') },
        ],
      },
      {
        id: 'topic',
        label: t('الموضوع والنقاط الأساسية', 'Topic and key points'),
        type: 'textarea',
        required: true,
      },
      {
        id: 'audience',
        label: t('القرّاء المستهدفون', 'Target readers'),
        type: 'text',
        required: false,
      },
      {
        id: 'tone',
        label: t('نبرة الكتابة', 'Writing tone'),
        type: 'select',
        required: true,
        options: [
          { value: 'formal', label: t('رسمية', 'Formal') },
          { value: 'conversational', label: t('حوارية', 'Conversational') },
          { value: 'persuasive', label: t('إقناعية', 'Persuasive') },
          { value: 'inspirational', label: t('ملهمة', 'Inspirational') },
          { value: 'humorous', label: t('فكاهية', 'Humorous') },
          { value: 'technical', label: t('تقنية', 'Technical') },
        ],
      },
      {
        id: 'length',
        label: t('الطول المطلوب', 'Desired length'),
        type: 'select',
        required: false,
        options: [
          { value: 'short', label: t('قصير', 'Short') },
          { value: 'medium', label: t('متوسط', 'Medium') },
          { value: 'long', label: t('طويل', 'Long') },
          { value: 'detailed', label: t('مفصّل جدًا', 'Very detailed') },
        ],
      },
    ],
  },
  {
    id: 'other',
    icon: 'Sparkles',
    label: t('أخرى', 'Other'),
    description: t('أي فكرة أخرى لا تندرج ضمن التصنيفات', 'Anything else not covered above'),
    isVisual: false,
    personaRole: t('خبير متعدد المجالات', 'a versatile expert assistant'),
    questions: [
      {
        id: 'topic',
        label: t('ما الذي تريد تحقيقه؟', 'What do you want to achieve?'),
        type: 'textarea',
        required: true,
      },
      {
        id: 'audience',
        label: t('لمن هذا الموجه؟', 'Who is this for?'),
        type: 'text',
        required: false,
      },
      {
        id: 'style',
        label: t('أي أسلوب أو قيود مفضلة؟', 'Any preferred style or constraints?'),
        type: 'textarea',
        required: false,
      },
    ],
  },
]

export function getProjectType(id: string): ProjectType | undefined {
  return PROJECT_TYPES.find((p) => p.id === id)
}
